<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Flight Search Test"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="10,638">
  <properties />
            <testcase name="FlightSearchTest" time="10,638" classname="com.w2a.testcases.FlightSearchTest">
                <failure type="java.lang.AssertionError"
                  message="did not expect to find [7] but found [5]"
              >
<![CDATA[java.lang.AssertionError: did not expect to find [7] but found [5]
  org.testng.Assert.fail(Assert.java:97)
  org.testng.Assert.failNotEquals(Assert.java:969)
  org.testng.Assert.assertEqualsImpl(Assert.java:136)
  org.testng.Assert.assertEquals(Assert.java:118)
  org.testng.Assert.assertEquals(Assert.java:563)
  com.w2a.errorcollectors.ErrorCollector.assertEquals(ErrorCollector.java:38)
  com.w2a.errorcollectors.ErrorCollector.verifyEquals(ErrorCollector.java:102)
  flightSearchTest(FlightSearchTest.java:18)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:658)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
  org.testng.TestRunner.privateRun(TestRunner.java:739)
  org.testng.TestRunner.run(TestRunner.java:589)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
  org.testng.SuiteRunner.run(SuiteRunner.java:302)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
  org.testng.TestNG.runSuites(TestNG.java:997)
  org.testng.TestNG.run(TestNG.java:965)
  org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
  org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
